package com.baraa.masroof.data.db

import com.baraa.masroof.data.db.MasroofDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Source- and schema-level safety checks for the Masroof Room database.
 *
 * These tests do **not** exercise Room at runtime — they verify the
 * configuration is correct so a future migration can be relied upon.
 *
 *  1. `fallbackToDestructiveMigration` must not appear in the source —
 *     silently wiping the DB is forbidden.
 *  2. The Room schema export must be present (generated by KSP at build
 *     time) so a future developer can author a migration against the
 *     captured schema.
 *  3. The current [MasroofDatabase] must declare at least one
 *     [androidx.room.migration.Migration] for the v1 → v2 bump.
 *  4. A [MigrationTestHelper]-based test (see
 *     [RoomMigrationTest]) is provided for device / instrumentation
 *     runs; this test confirms the class compiles and is referenced.
 */
class RoomSchemaSafetyTest {

    @Test
    fun noDestructiveMigrationInDatabaseSource() {
        // The source file is read from the project root regardless of the
        // working directory Gradle uses for tests.
        val candidates = listOf(
            "src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt",
            "../src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt",
            "app/src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt"
        )
        val sourceFile = candidates.map { File(it) }.firstOrNull { it.exists() }
            ?: error("Could not find MasroofDatabase.kt in any of: $candidates")
        val source = sourceFile.readText()
        assertFalse(
            "fallbackToDestructiveMigration() must not be called in MasroofDatabase.kt",
            Regex("""\.fallbackToDestructiveMigration\s*\(""").containsMatchIn(source)
        )
        assertTrue(
            "addMigrations must be configured",
            source.contains("addMigrations")
        )
    }

    @Test
    fun databaseVersionIsAtLeastTwo() {
        // The v1 -> v2 migration added the transactionSimilarityKey column;
        // the v2 -> v3 migration added the categories / merchant_memory /
        // financial_accounts tables and the 7 new transaction columns.
        val sourceFile = File("src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt")
        val source = sourceFile.readText()
        val match = Regex("version\\s*=\\s*(\\d+)").find(source)
        assertTrue("database must declare a version", match != null)
        val version = match!!.groupValues[1].toInt()
        assertTrue("database version must be >= 2 (was $version)", version >= 2)
    }

    @Test
    fun migrationOneToTwoIsDeclared() {
        val sourceFile = File("src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt")
        val source = sourceFile.readText()
        assertTrue(
            "MasroofDatabase must expose a MIGRATION_1_2 constant",
            source.contains("MIGRATION_1_2")
        )
        // The migration must add the new column.
        assertTrue(
            "MIGRATION_1_2 must ADD COLUMN transactionSimilarityKey",
            source.contains("ADD COLUMN `transactionSimilarityKey`") ||
                source.contains("ADD COLUMN transactionSimilarityKey")
        )
    }

    @Test
    fun schemaExportDirectoryContainsAllVersions() {
        // The KSP arg `room.schemaLocation = $projectDir/schemas` is
        // configured in app/build.gradle.kts. After a clean build it
        // produces one JSON per database version.
        val schemaRoot = File("schemas/com.baraa.masroof.data.db.MasroofDatabase")
        val altSchemaRoot = File("app/schemas/com.baraa.masroof.data.db.MasroofDatabase")
        val root = when {
            schemaRoot.exists() -> schemaRoot
            altSchemaRoot.exists() -> altSchemaRoot
            else -> error("Schema export directory not found. Looked in: $schemaRoot and $altSchemaRoot")
        }
        val v1 = File(root, "1.json")
        val v2 = File(root, "2.json")
        val v3 = File(root, "3.json")
        assertTrue("v1 schema must exist: $v1", v1.exists())
        assertTrue("v2 schema must exist: $v2", v2.exists())
        assertTrue("v3 schema must exist: $v3", v3.exists())
        assertTrue("v20 schema must exist", File(root, "20.json").exists())
        assertTrue("v21 schema must exist", File(root, "21.json").exists())
        // v22 is exported by KSP on compile after dropping sender_message_patterns.
        assertTrue("v22 schema must exist after compile", File(root, "22.json").exists())
        assertTrue("v24 schema must exist after compile", File(root, "24.json").exists())
        val v25 = File(root, "25.json")
        assertTrue("v25 schema must exist after compile", v25.exists())
        val v25Json = v25.readText()
        assertTrue("v25 schema must contain canonicalKey", v25Json.contains("canonicalKey"))
        assertTrue(
            "v25 schema must declare the unique canonical index",
            v25Json.contains("index_message_pattern_definitions_senderProfileId_canonicalKey"),
        )
        // v26 keeps the same columns; key semantics change in migration only.
        assertTrue("v26 schema must exist after compile", File(root, "26.json").exists())
        // v3 must contain the new transaction columns and the new tables.
        val v3Json = v3.readText()
        assertTrue(
            "v3 schema must contain financialTreatment",
            v3Json.contains("financialTreatment")
        )
        assertTrue(
            "v3 schema must contain categoryId",
            v3Json.contains("categoryId")
        )
        assertTrue(
            "v3 schema must contain the categories table",
            v3Json.contains("\"categories\"")
        )
        assertTrue(
            "v3 schema must contain the merchant_memory table",
            v3Json.contains("\"merchant_memory\"")
        )
        assertTrue(
            "v3 schema must contain the financial_accounts table",
            v3Json.contains("\"financial_accounts\"")
        )
    }
}
