package com.baraa.masroof.data.db

import com.baraa.masroof.data.db.MasroofDatabase
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertTrue
import org.junit.Test
import java.io.File

/**
 * Source- and schema-level safety checks for the Masroof Room database.
 *
 * These tests do **not** exercise Room at runtime — they verify the
 * configuration is correct so a future migration can be relied upon.
 *
 *  1. `fallbackToDestructiveMigration` must not appear in the source —
 *     silently wiping the DB is forbidden.
 *  2. The Room schema export must be present (generated by KSP at build
 *     time) so a future developer can author a migration against the
 *     captured schema.
 *  3. The current [MasroofDatabase] must declare at least one
 *     [androidx.room.migration.Migration] for the v1 → v2 bump.
 *  4. A [MigrationTestHelper]-based test (see
 *     [RoomMigrationTest]) is provided for device / instrumentation
 *     runs; this test confirms the class compiles and is referenced.
 */
class RoomSchemaSafetyTest {

    @Test
    fun noDestructiveMigrationInDatabaseSource() {
        // The source file is read from the project root regardless of the
        // working directory Gradle uses for tests.
        val candidates = listOf(
            "src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt",
            "../src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt",
            "app/src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt",
        )
        val sourceFile = candidates.map { File(it) }.firstOrNull { it.exists() }
            ?: error("Could not find MasroofDatabase.kt in any of: $candidates")
        val source = sourceFile.readText()
        assertFalse(
            "fallbackToDestructiveMigration must not appear in MasroofDatabase.kt",
            source.contains("fallbackToDestructiveMigration"),
        )
        assertTrue(
            "addMigrations must be configured",
            source.contains("addMigrations"),
        )
    }

    @Test
    fun databaseVersionIsAtLeastTwo() {
        // The v1 → v2 migration added the transactionSimilarityKey column.
        // The current version must be at least 2 to reflect that bump.
        val kspGenerated = File("build/generated/ksp/release/kotlin/com/baraa/masroof/data/db/MasroofDatabase_Impl.java")
        val alt = File("build/generated/ksp/debug/kotlin/com/baraa.masroof.data.db.MasroofDatabase_Impl.java")
        // We don't actually need the impl — the version is in the annotation
        // on the source file. Just assert the source has version = 2.
        val sourceFile = File("src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt")
        val source = sourceFile.readText()
        assertTrue("database must declare version 2 or higher", source.contains("version = 2"))
    }

    @Test
    fun migrationOneToTwoIsDeclared() {
        val sourceFile = File("src/main/kotlin/com/baraa/masroof/data/db/MasroofDatabase.kt")
        val source = sourceFile.readText()
        assertTrue(
            "MasroofDatabase must expose a MIGRATION_1_2 constant",
            source.contains("MIGRATION_1_2"),
        )
        // The migration must add the new column.
        assertTrue(
            "MIGRATION_1_2 must ADD COLUMN transactionSimilarityKey",
            source.contains("ADD COLUMN `transactionSimilarityKey`") ||
                source.contains("ADD COLUMN transactionSimilarityKey"),
        )
    }

    @Test
    fun schemaExportDirectoryContainsV1AndV2Schemas() {
        // The KSP arg `room.schemaLocation = $projectDir/schemas` is
        // configured in app/build.gradle.kts. After a clean build it
        // produces one JSON per database version.
        val schemaRoot = File("schemas/com.baraa.masroof.data.db.MasroofDatabase")
        val altSchemaRoot = File("app/schemas/com.baraa.masroof.data.db.MasroofDatabase")
        val root = when {
            schemaRoot.exists() -> schemaRoot
            altSchemaRoot.exists() -> altSchemaRoot
            else -> error("Schema export directory not found. Looked in: $schemaRoot and $altSchemaRoot")
        }
        val v1 = File(root, "1.json")
        val v2 = File(root, "2.json")
        assertTrue("v1 schema must exist: $v1", v1.exists())
        assertTrue("v2 schema must exist: $v2", v2.exists())
        // The two schemas must differ in the table definition (v2 adds a column).
        val v1Json = v1.readText()
        val v2Json = v2.readText()
        assertNotEquals("v1 and v2 schemas must differ", v1Json, v2Json)
        // v2 must reference the new column.
        assertTrue(
            "v2 schema must contain transactionSimilarityKey",
            v2Json.contains("transactionSimilarityKey"),
        )
        assertFalse(
            "v1 schema must not contain transactionSimilarityKey",
            v1Json.contains("transactionSimilarityKey"),
        )
    }
}
